name: CI

on:
  push:
    branches:    
      - develop

jobs:
  build-and-deploy:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Ionic
      run: npm install -g ionic
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build:browser
    - name: whats here
      run: ls -l
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "www"
        remoteDir: "."
