name: CICD

on:
  push:
    branches:    
      - master

jobs:
  FTP-Deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Ionic
      run: npm install -g ionic
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build:browser
    - name: Upload to ftp
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        known-hosts: ${{ secrets.SSH_HASH }}
        local-dir: www
